In [2]:
def media(l):
    return sum(l)/len(l)

media([1,2,3])

2.0

In [17]:
import numpy as np

In [18]:
a = np.asarray([1,2,3,4,5])
print(a, type(a))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [8]:
a = [1,2,3,4,5]
b = a / 5

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [10]:
b = [e/5 for e in a]
b

[0.2, 0.4, 0.6, 0.8, 1.0]

In [19]:
c = np.asarray(a)


In [20]:
print(c / 5)
print(c * 5)
print(c + 100)

[0.2 0.4 0.6 0.8 1. ]
[ 5 10 15 20 25]
[101 102 103 104 105]


In [24]:
c = [[1,2,3],[4,5,6],[7,8,9]]
c[1][1]

5

In [30]:
q = np.asarray(c)
print(q)
print(q.size)
print(q.shape)
print(len(q.shape))
print(q.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)
2
int64


In [37]:
x = np.eye(4) * 100
x

array([[100.,   0.,   0.,   0.],
       [  0., 100.,   0.,   0.],
       [  0.,   0., 100.,   0.],
       [  0.,   0.,   0., 100.]])

In [42]:
# Fila 0
x[0]
# Columna 0
x[:,0]
# Indice específico
x[2,2]

100.0

In [46]:
np.ones((3,4,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [48]:
m = np.random.random((3,4))
m

array([[0.70916699, 0.1463563 , 0.8378459 , 0.92074815],
       [0.93919746, 0.62931775, 0.75099149, 0.55783362],
       [0.85725088, 0.87808749, 0.24243627, 0.48318128]])

In [59]:
# Generar un numpy array (3,3) con numeros aleatorios en la diagonal que
# esten contenidos en el intevalo [100,200]

m = np.eye(3) * (np.random.random((3,3))*100 + 100)
 
m

array([[159.50905879,   0.        ,   0.        ],
       [  0.        , 181.13822421,   0.        ],
       [  0.        ,   0.        , 150.09087759]])

In [63]:
for e in m:
    print(type(e))
    for j in e:
        print(j,type(j))

<class 'numpy.ndarray'>
159.50905879011952 <class 'numpy.float64'>
0.0 <class 'numpy.float64'>
0.0 <class 'numpy.float64'>
<class 'numpy.ndarray'>
0.0 <class 'numpy.float64'>
181.1382242066663 <class 'numpy.float64'>
0.0 <class 'numpy.float64'>
<class 'numpy.ndarray'>
0.0 <class 'numpy.float64'>
0.0 <class 'numpy.float64'>
150.090877586047 <class 'numpy.float64'>


In [66]:
type(m.tolist())

list

In [68]:
m = np.random.random((3,4))
m

array([[0.69699029, 0.45936561, 0.08161418, 0.72754227],
       [0.16082525, 0.01898503, 0.16013031, 0.47810111],
       [0.32356157, 0.44946678, 0.02108365, 0.42226815]])

In [72]:
# np.sum(m) is the same as:
m.sum()

3.99993419485244

In [73]:
m.sum(axis=0)

array([1.18137711, 0.92781742, 0.26282814, 1.62791153])

In [74]:
m.sum(axis=1)

array([1.96551234, 0.8180417 , 1.21638015])

In [75]:
m.shape

(3, 4)

In [83]:
w = np.random.random((3,3,3))
w

array([[[0.01846446, 0.0515639 , 0.09367027],
        [0.09576186, 0.94931992, 0.7557277 ],
        [0.27215196, 0.36197524, 0.53121614]],

       [[0.69390936, 0.34796727, 0.90752707],
        [0.36089244, 0.63466814, 0.65819909],
        [0.92457047, 0.33388633, 0.82125651]],

       [[0.45143395, 0.95170475, 0.44642604],
        [0.46126714, 0.16128045, 0.19228093],
        [0.45132936, 0.70206705, 0.90214938]]])

In [84]:
w.sum(axis=0)

array([[1.16380777, 1.35123593, 1.44762338],
       [0.91792144, 1.74526851, 1.60620772],
       [1.64805179, 1.39792862, 2.25462202]])

In [85]:
a = np.random.random((3,3))
b = np.random.random((3,3))

In [91]:
np.concatenate([a,b])

array([[0.67688198, 0.78973112, 0.37653789],
       [0.52520219, 0.95354256, 0.34481502],
       [0.03796804, 0.72014939, 0.66085816],
       [0.13750139, 0.33303971, 0.0213671 ],
       [0.05015196, 0.54695946, 0.60208508],
       [0.24514689, 0.44355272, 0.3035735 ]])

In [90]:
np.concatenate([a,b], axis=1)

array([[0.67688198, 0.78973112, 0.37653789, 0.13750139, 0.33303971,
        0.0213671 ],
       [0.52520219, 0.95354256, 0.34481502, 0.05015196, 0.54695946,
        0.60208508],
       [0.03796804, 0.72014939, 0.66085816, 0.24514689, 0.44355272,
        0.3035735 ]])

In [95]:
w = np.eye(5)
w.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [97]:
np.concatenate([a,b], axis=1).T

array([[0.67688198, 0.52520219, 0.03796804],
       [0.78973112, 0.95354256, 0.72014939],
       [0.37653789, 0.34481502, 0.66085816],
       [0.13750139, 0.05015196, 0.24514689],
       [0.33303971, 0.54695946, 0.44355272],
       [0.0213671 , 0.60208508, 0.3035735 ]])

In [101]:
a = np.arange(10) # range()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
a.dtype

dtype('int64')

In [106]:
a = np.arange(10, dtype="float")
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [122]:
b = np.arange(1,10)
print(b,b.size)
type(b)

[1 2 3 4 5 6 7 8 9] 9


numpy.ndarray

In [112]:
b.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
z = np.arange(10).reshape((5,2))
z

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [119]:
z.std(axis=1)

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [125]:
z = np.arange(9).reshape((3,3))
print(z*2) # 2*z
print(z*z) # element-wise product

# https://en.wikipedia.org/wiki/Dot_product
print(np.dot(z,z)) # <-- multiplicacion de matrices 

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [129]:
a = np.arange(10)
a / 0

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [136]:
a = np.arange(1,10)
print(a)
b = a.reshape((3,3))
print(a)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
